# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dovid.io" # the base hostname & protocol for your site
excerpt_separator: "<!-- more -->"


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Dovid.io
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Sito web personale di Umberto D'Ovidio  " # used by search engines

  # Header and footer text
  header_text: >
     <h1>Dovid.io</h1>
     <p>Le fantastiche avventure di un programmatore in erba</p>
  header_text_feature_image: 
      img/header_home.png
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> Copyright 2017 Umberto D'Ovidio

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "Cyborg101"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/umberto-d-ovidio-b6b276125"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "UmbertoDOvidio"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-84012198-1
  disqus_shortname: dovid-io
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Seguici on"
  str_rss_follow: "Segui RSS feed"
  str_email: "Email"
  str_next: "Prossimo"
  str_prev: "Precedente"
  str_continue_reading: "Continua a leggere"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
