# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dovid.io" # the base hostname & protocol for your site
excerpt_separator: "<!-- more -->"
lang: it_IT
env: production
title: Dovid.io - Sviluppo mobile e web by Umberto D'Ovidio

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Dovid.io - Sviluppo mobile e web
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Articoli e tutorial scritti a regola d'arte su programmazione web lato server e client. Approfondimenti su linguaggi come Java, Kotlin, Swift, Javascript." # used by search engines

  # Header and footer text
  header_text: >
     <h2>Dovid.io</h2>
     <p>Parliamo di sviluppo web, mobile e correlati.</p>
  header_text_feature_image: 
      img/header_home.png
  footer_text: >
<<<<<<< HEAD
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> - Copyright 2018 Umberto D'Ovidio
=======
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>
>>>>>>> e5db7cc0d973b756cbb5e4915d773ab08ef788f7

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
<<<<<<< HEAD
  github: "Cyborg101"
=======
  gitlab:
  github: "rohanchandra/type-theme"
>>>>>>> e5db7cc0d973b756cbb5e4915d773ab08ef788f7
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/umberto-d-ovidio-b6b276125"
  pinterest:
  quora: "Umberto-DOvidio"
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "UmbertoDOvidio"
  wordpress:
  youtube:

  # Scripts
<<<<<<< HEAD
  google_analytics: UA-84012198-1
  disqus_shortname: dovid-io
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: false # Enable if using math markup
=======
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature
>>>>>>> e5db7cc0d973b756cbb5e4915d773ab08ef788f7

  # Localization strings
  str_follow_on: "Seguici on"
  str_rss_follow: "Segui RSS feed"
  str_email: "Email"
<<<<<<< HEAD
  str_next: "Successivo"
  str_prev: "Precedente"
  str_continue_reading: "Continua a leggere"
=======
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."
>>>>>>> e5db7cc0d973b756cbb5e4915d773ab08ef788f7

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 8
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
<<<<<<< HEAD
gems: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]
=======
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
>>>>>>> e5db7cc0d973b756cbb5e4915d773ab08ef788f7
